In [19]:
from math import atan

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import tensorflow as tf
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np

In [21]:
import tensorflow as tf
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

In [22]:
import cv2
import os
import dlib
import re
from PIL import Image

In [24]:
def shape_to_np(shape, dtype="int"):
    # initialize the list of (x, y)-coordinates
    coords = np.zeros((shape.num_parts, 2), dtype=dtype)

    # loop over all facial landmarks and convert them
    # to a 2-tuple of (x, y)-coordinates
    for i in range(0, shape.num_parts):
        coords[i] = (shape.part(i).x, shape.part(i).y)

    # return the list of (x, y)-coordinates
    return coords

In [25]:
def rect_to_bb(rect):
    # take a bounding predicted by dlib and convert it
    # to the format (x, y, w, h) as we would normally do
    # with OpenCV
    x = rect.left()
    y = rect.top()
    w = rect.right() - x
    h = rect.bottom() - y

    # return a tuple of (x, y, w, h)
    return (x, y, w, h)

In [26]:
def run_dlib_shape(image):
    # in this function we load the image, detect the landmarks of the face, and then return the image and the landmarks
    # load the input image, resize it, and convert it to grayscale
    resized_image = image.astype('uint8')

    gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)
    gray = gray.astype('uint8')

    # detect faces in the grayscale image
    rects = detector(gray, 1)
    num_faces = len(rects)

    if num_faces == 0:
        return None, resized_image

    face_areas = np.zeros((1, num_faces))
    face_shapes = np.zeros((136, num_faces), dtype=np.int64)

    # loop over the face detections
    for (i, rect) in enumerate(rects):
        # determine the facial landmarks for the face region, then
        # convert the facial landmark (x, y)-coordinates to a NumPy
        # array
        temp_shape = predictor(gray, rect)
        temp_shape = shape_to_np(temp_shape)

        # convert dlib's rectangle to a OpenCV-style bounding box
        # [i.e., (x, y, w, h)],
        #   (x, y, w, h) = face_utils.rect_to_bb(rect)
        (x, y, w, h) = rect_to_bb(rect)
        face_shapes[:, i] = np.reshape(temp_shape, [136])
        face_areas[0, i] = w * h
    # find largest face and keep
    dlibout = np.reshape(np.transpose(face_shapes[:, np.argmax(face_areas)]), [68, 2])

    return dlibout, resized_image

# Get the stored X and fs values (facial landmarks and face shape labels)

In [18]:
%store -r

In [72]:
y_fs

array([2.5, 2.5, 0.5, ..., 1.5, 1.5, 1.5])

In [73]:
y = 2*y_fs -1

In [74]:
y

array([4., 4., 0., ..., 2., 2., 2.])

In [5]:
X.shape

(8194, 68, 2)

# Compute the 19 features to be used in the dataset

These features are calculated using a set of formulas obtained from a research paper. I will be defining that formula in the report.

In [35]:
feature_1 = [(element[8][1]-element[19][1])/np.linalg.norm(element[0] - element[16]) for element in X]

In [53]:
feature_1

[0.9300094261677986,
 0.9528752358292977,
 0.9016258828398552,
 0.8537427780456707,
 0.8207544036231031,
 0.8879218233316102,
 0.8128515980190735,
 0.874108154015099,
 0.9095464574402502,
 0.7717277333111592,
 0.9152396304968694,
 0.9246083772029406,
 0.8396636785481033,
 0.8438742459786835,
 0.8709034521808375,
 0.713299838953454,
 0.8941021782968169,
 0.8609915372563222,
 0.8603217703090142,
 0.7788985439163326,
 0.7837746898356402,
 0.7889276199351819,
 0.8314876315471742,
 0.8020724546032,
 0.8420908641348674,
 0.8384232275214017,
 0.8010927461519324,
 0.9360306918810493,
 0.8270946201546931,
 0.9075144508670521,
 0.8221714724630638,
 0.9005387422259653,
 0.923130220299432,
 0.8080166374266439,
 1.0050384021424366,
 0.8505041649150354,
 0.8602143911560362,
 0.8322853524821389,
 0.8161685233205218,
 0.8191959655681856,
 0.8917746465412787,
 0.8017622327880075,
 0.7997911022584094,
 0.8100104689671047,
 0.8894416382308379,
 0.8603351955307262,
 1.0962410101350766,
 0.8530706851747485

In [36]:
feature_2 = [(np.linalg.norm(element[4] - element[12]))/(np.linalg.norm(element[0] - element[16])) for element in X]

In [55]:
feature_2

[0.8535431588882618,
 0.7587710211233296,
 0.6940002228717751,
 0.7198430709853465,
 0.7109586478206036,
 0.726167098726938,
 0.7194998604893803,
 0.7546305345630873,
 0.7740443603255741,
 0.722815412185804,
 0.7796485741269629,
 0.7686676079214544,
 0.6849887903945053,
 0.751417106845166,
 0.772870830763914,
 0.7188081737899598,
 0.6647984850377241,
 0.8054628503432287,
 0.70398829935065,
 0.7016480881969467,
 0.7157105145206858,
 0.7227821547549889,
 0.7452941517714332,
 0.7294543312100055,
 0.742769445808892,
 0.7669649888473704,
 0.6741134263192373,
 0.6919464772134025,
 0.7704286509141387,
 0.6994458506407406,
 0.7055338773526997,
 0.7900625082004903,
 0.7235989950366001,
 0.7150311580552478,
 0.8234696046491466,
 0.8000219196189349,
 0.7933616936247151,
 0.6764595360405203,
 0.7085822972733054,
 0.7289989813724053,
 0.6766453444192194,
 0.7528394180599213,
 0.7314383920335924,
 0.7068150199031201,
 0.74057477748958,
 0.7207569996894615,
 0.7491297018981039,
 0.7257467023128457,
 

In [37]:
feature_3 = [(np.linalg.norm(element[8] - element[57]))/(np.linalg.norm(element[4] - element[12])) for element in X]

In [57]:
feature_3

[0.3060991623025956,
 0.2094458307923457,
 0.1810967482813143,
 0.1788987177729337,
 0.22777988238262373,
 0.23951179473392467,
 0.18046343066790324,
 0.21007136652966157,
 0.2491128455592316,
 0.18060770149570396,
 0.18115942028985507,
 0.2935852166450892,
 0.20983244889125302,
 0.1852498205293422,
 0.238593696775623,
 0.15951789907693162,
 0.23073209014841065,
 0.2621534596606752,
 0.1919343401582685,
 0.1896079007204609,
 0.20693273953189795,
 0.19182110058403284,
 0.16514304215895173,
 0.15707875644382344,
 0.1812509818678693,
 0.1815666737676846,
 0.1968655509148899,
 0.1354809971917486,
 0.23123193571063136,
 0.2245060142103319,
 0.18897051994571928,
 0.23775642443352232,
 0.22766705489330252,
 0.20340784682024984,
 0.28879319070360837,
 0.27091418459143857,
 0.23938320252746964,
 0.18241227957067452,
 0.16799001372346847,
 0.24847885572366465,
 0.14377473767873744,
 0.16793001374957145,
 0.21087958814313626,
 0.2277196868524017,
 0.20239117754696526,
 0.22690732251938633,
 0.298

In [38]:
feature_4 = [atan(abs(element[0][0] - element[8][0])/abs(element[0][1] - element[8][1])) for element in X]

In [39]:
feature_5 = [atan(abs(element[1][0] - element[8][0])/abs(element[1][1] - element[8][1])) for element in X]

In [40]:
feature_6 = [atan(abs(element[2][0] - element[8][0])/abs(element[2][1] - element[8][1])) for element in X]

In [41]:
feature_7 = [atan(abs(element[3][0] - element[8][0])/abs(element[3][1] - element[8][1])) for element in X]

In [42]:
feature_8 = [atan(abs(element[4][0] - element[8][0])/abs(element[4][1] - element[8][1])) for element in X]

In [43]:
feature_9 = [atan(abs(element[5][0] - element[8][0])/abs(element[5][1] - element[8][1])) for element in X]

In [44]:
feature_10 = [atan(abs(element[6][0] - element[8][0])/abs(element[6][1] - element[8][1])) for element in X]

C:\Users\pda12\AppData\Local\Temp\ipykernel_57012\672821867.py:1: RuntimeWarning: divide by zero encountered in longlong_scalars
  feature_10 = [atan(abs(element[6][0] - element[8][0])/abs(element[6][1] - element[8][1])) for element in X]


In [45]:
feature_11 = [atan(abs(element[7][0] - element[8][0])/abs(element[7][1] - element[8][1])) for element in X]

C:\Users\pda12\AppData\Local\Temp\ipykernel_57012\1792554841.py:1: RuntimeWarning: divide by zero encountered in longlong_scalars
  feature_11 = [atan(abs(element[7][0] - element[8][0])/abs(element[7][1] - element[8][1])) for element in X]


In [46]:
feature_12 = [atan(abs(element[9][0] - element[8][0])/abs(element[9][1] - element[8][1])) for element in X]

C:\Users\pda12\AppData\Local\Temp\ipykernel_57012\3561130787.py:1: RuntimeWarning: divide by zero encountered in longlong_scalars
  feature_12 = [atan(abs(element[9][0] - element[8][0])/abs(element[9][1] - element[8][1])) for element in X]


In [47]:
feature_13 = [atan(abs(element[10][0] - element[8][0])/abs(element[10][1] - element[8][1])) for element in X]

In [48]:
feature_14 = [atan(abs(element[11][0] - element[8][0])/abs(element[11][1] - element[8][1])) for element in X]

In [49]:
feature_15 = [atan(abs(element[12][0] - element[8][0])/abs(element[12][1] - element[8][1])) for element in X]

In [50]:
feature_16 = [atan(abs(element[13][0] - element[8][0])/abs(element[13][1] - element[8][1])) for element in X]

In [51]:
feature_17 = [atan(abs(element[14][0] - element[8][0])/abs(element[14][1] - element[8][1])) for element in X]

In [52]:
feature_18 = [atan(abs(element[15][0] - element[8][0])/abs(element[15][1] - element[8][1])) for element in X]

In [53]:
feature_19 = [atan(abs(element[16][0] - element[8][0])/abs(element[16][1] - element[8][1])) for element in X]

In [54]:
images_features = np.ones([8194, 19])

In [55]:
for i in range(len(feature_1)):
    images_features[i] = (feature_1[i], feature_2[i], feature_3[i], feature_4[i], feature_5[i], feature_6[i],feature_7[i], feature_8[i], feature_9[i],feature_10[i], feature_11[i], feature_12[i],feature_13[i], feature_14[i], feature_15[i],feature_16[i], feature_17[i], feature_18[i],feature_19[i])

In [56]:
images_features

array([[0.93000943, 0.85354316, 0.30609916, ..., 0.68855916, 0.60554466,
        0.52984907],
       [0.95287524, 0.75877102, 0.20944583, ..., 0.76130644, 0.65080025,
        0.57210288],
       [0.90162588, 0.69400022, 0.18109675, ..., 0.75715709, 0.66828942,
        0.58966098],
       ...,
       [1.02874245, 0.8046798 , 0.2706945 , ..., 0.59053424, 0.52975324,
        0.4697825 ],
       [0.98788011, 0.73491111, 0.2464392 , ..., 0.686952  , 0.62111679,
        0.56068699],
       [0.91806586, 0.70170639, 0.1751983 , ..., 0.75976275, 0.69865982,
        0.62253433]])

In [109]:
training_features.shape

(7374, 19)